<?xml version="1.0" encoding="UTF-8"?>
<!--Xml-документ, хранящий информацию о всех музеях, размещенных на сайте-->
<!DOCTYPE museums [
<!ELEMENT museums (museum*)>
<!ELEMENT museum (title, info, picture+, district, subjects, time, address, email, cost, number)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT district (#PCDATA)>
<!ELEMENT subjects (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT number (#PCDATA)>
]>

<museums>
	<museum>
		<title>Алисон Бекер</title>
		<info>
Алиссон Рамзес Бекер (порт. Alisson Ramses Becker; родился 2 октября 1992 года в Нову-Амбургу, Бразилия), более известный как Алиссон — бразильский футболист немецкого происхождения, вратарь клуба «Ливерпуль» и сборной Бразилии. Участник чемпионата мира 2018 года.
Алиссон — воспитанник клуба «Интернасьонал». 17 февраля 2013 года в матче Лиги Гаушу против «Крузейро» из Порту-Алегри он дебютировал за основную команду. 25 августа в поединке против «Гояса» Алиссон дебютировал в бразильской Серии A. В 2015 году после того, как Дида завершил карьеру, он стал основным вратарём команды. В составе «Интернасьонала» Алиссон трижды выиграл Лигу Гаушу.
Уже в начале 2018 года заинтересованность во вратаре проявили испанская «Барселона», французский «Пари Сен-Жермен» и английский «Ливерпуль». Летом того же года Алиссон подписал шестилетний контракт с последним. Сумма трансфера составила 66,8 млн фунтов (72,5 млн евро), что сделало Бекера самым дорогим вратарём в истории (прежнее достижение принадлежало итальянцу Джанлуиджи Буффону и продержалось 17 лет).
		</info>
		<picture>artmuseum1.jpg</picture>
		<district>Вратарь</district>
		<subjects>Травмирован</subjects>
		<time>28 </time>
		<address>ул. Ленина, 20</address>
		<email>nmmrb@bk.ru</email>
		<cost>90 млн</cost>
		<number>+375 17 327 71 63</number>
	</museum>
	<museum>
		<title>Музей истории Великой Отечественной войны</title>
		<info>Сбор экспонатов для будущего Белорусского государственного музея истории Великой Отечественной войны начался еще в разгар военных действий. Уже в 1942 году в Москве было принято решение создать Комиссию по сбору документов и материалов Отечественной войны. 

Материалы собирались по двум основным темам — «Вероломное вторжение германского фашизма в пределы Советского Союза» и «Героическая борьба трудящихся БССР с германскими захватчиками». Благодаря разрыву в линии фронта — так называемым «Витебским воротам» — и освобождению прифронтовых районов партизанами, уже через полгода в Москве была открыта выставка «Белоруссия живет, Белоруссия борется, Белоруссия была и будет советской». Здесь были представлены фотографии, вещи солдат, документы и художественные произведения, посвященные войне. 

В 1943 году встал вопрос об открытии музея Отечественной войны на территории Беларуси. Вскоре в Минск была привезена выставка «Белоруссия живет…», и на ее базе организован первый музей ВОВ в здании Государственного исторического музея Москвы.

В 1944 году музею было выделено отдельное здание — Дом профсоюзов на пл. Свободы, а директором назначили Василия Стальнова. В 1966 году экспозиция переехала в новое здание на Ленинском проспекте (сейчас — проспект Независимости). 

3 июля 2014 года Музей истории Великой Отечественной войны переехал в новое здание на перекрёстке проспектов Машерова и Победителей. Новый музей — это 10 выставочных залов и более 140 тысяч экспонатов, многие из которых не имеют аналогов. Он составляет единый архитектурный ансамбль с обелиском «Минск — город-герой». Главный фасад здания выполнен в виде лучей салюта Победы. Каждый из них направлен к центру обелиска и содержит скульптурные рельефы о военных событиях. Автор проекта и архитектор — Виктор Крамаренко.

Все экспозиционные залы выстроены по хронологии событий — от довоенных до дней восстановления республики. Во всем здании есть мультимедийные комплексы с инсталляциями и плазменными экранами. Сотрудники музея оказывают множество услуг: от проведения разноплановых экскурсий до индивидуальных консультаций и предоставления площадки для имитации военной стрельбы. Также в экспозиционных залах можно воспользоваться аудиогидами. 

Музей Великой Отечественной войны в Минске — это место, где просыпается чувство патриотизма, где помнят, какой ценой далась белорусам свобода и независимость, где верят в высшие духовные ценности и знают, насколько важно помнить.</info>
		<picture>warmuseum.jpg</picture>
		<picture>warmuseum1.jpg</picture>
		<district>Центральный</district>
		<subjects>Музей истории</subjects>
		<time>10.00 – 18.00</time>
		<address>пр-т. Победителей 8</address>
		<email>museumww2@tut.by</email>
		<cost>9.0</cost>
		<number>8 017 327-11-66</number>
	</museum>
	<museum>
		<title>Национальный исторический музей Республики Беларусь</title>
		<info>Национальный исторический музей Республики Беларусь – один из наиболее популярных музеев страны. В его собрании находится самая многочисленная музейная коллекция в Беларуси – это более 400 тысяч единиц хранения. В музейных фондах и на выставочных площадках хранится уникальная коллекция кладов из разных уголков Беларуси, ценные документы, старопечатные книги, слуцкие пояса, коллекция музыкальных инструментов и оружия, ценная фарфоровая посуда и многое другое.

В структуру Национального исторического музея также входят 5 филиалов, деятельность которых отражает развитие белорусского общества в самых разных аспектах культуры:
Дом-музей I съезда РСДРП, Музей истории белорусского кино, Музей истории театральной и музыкальной культуры Беларуси, Музей природы и экологии Беларуси, Музей современной белорусской государственности.

Постоянная экспозиция:
Экспозиция и тематические долгосрочные выставочные проекты Национального исторического музея знакомят посетителей с различными аспектами жизни населения Беларуси с древнейших времен до ХХ в.

Временные выставки:
Среди приоритетов Национального исторического музея - организация ярких для культурной жизни Минска и Беларуси выставочных проектов. Узнай актуальные временные выставки нашего музея!

Музейная сокровищница:
Значительную часть музейной коллекции составляют уникальные предметы не только белорусского, но и общемирового значения.</info>
		<picture>historicalmuseum.jpg</picture>
		<picture>historicalmuseum1.jpg</picture>
		<district>Ленинский</district>
		<subjects>Музей истории</subjects>
		<time>11.00 – 18.30</time>
		<address>ул. К.Маркса,12</address>
		<email>histmuseum@tut.by</email>
		<cost>20.0</cost>
		<number>+375 17 327-43-22</number>
	</museum>
	<museum>
		<title>Музей истории города Минска</title>
		<info>Музей расположен в историческом центре Минска на территории Верхнего города. Здание является памятником архитектуры XIX в. Для посетителей музей открыл свои двери 8 мая 2010 г. экспозицией «Художник Гражданин. Герой», посвящённой Герою Беларуси, народному художнику Беларуси, Почетному гражданину города Минска Михаилу Андреевичу Савицкому. Фонды музея включают более 7 тысяч единиц хранения (2012). Их основу составляют коллекции археологических раскопок Минска XI-XIX вв., предметов городского быта, фотоаппаратов конца XIX-XX вв., живописи, графики, декоративно-прикладного искусства, мемориальные собрания знаменитых личностей. 
			В структуру музея входят: Минская городская ратуша (пл. Свободы, 2а), Художественная галерея Михаила Савицкого (пл. Свободы, 15), Городская художественная галерея произведений Л.Д. Щемелёва (пр. Рокоссовского, 49), Мастерская-музей народного художника Беларуси скульптора Ивана Миско (ул. Интернациональная, 11а), Флигель Лошицкого усадебно-паркового комплекса (проезд Чижевских, 10). В музее организуются сменные тематические выставки, в том числе международные, на основе собраний коллекционеров, художников, фотографов, разных организаций и учреждений, а также разнообразные творческие проекты: концерты, семинары, конференции, акции, пленеры.
		</info>
		<picture>minskmuseum.jpg</picture>
		<picture>minskmuseum1.jpg</picture>
		<district>Центральный</district>
		<subjects>Музей истории</subjects>
		<time>11.00 – 19.00</time>
		<address>площадь Свободы, 15</address>
		<email>muzejminska@gmail.com</email>
		<cost>4.0</cost>
		<number>+375 17 321-24-30</number>
	</museum>
	<museum>
		<title>Национальный центр современных искусств Республики Беларусь</title>
		<info>Национальный центр современных искусств Республики Беларусь – крупнейшее государственное учреждение Беларуси, деятельность которого сосредоточена исключительно на искусстве ХХ-ХХІ веков. Это место, где идет активная работа по изучению, экспонированию и популяризации отечественного современного искусства.

Постоянная коллекция Национального центра насчитывает почти 5000 художественных произведений и отражает основные этапы становления и развития белорусского современного искусства второй половины ХХ века. В этом собрании представлены работы известных белорусских живописцев, графиков и скульпторов. Выставочные площадки ориентированы на презентацию экспериментальных направлений в различных видах искусства (изобразительном, театральном, музыкальном, дизайне, компьютерной графике и иных) и творчества художников, с которыми белорусский зритель еще не достаточно знаком.

Национальный центр современных искусств – это отличное место для открытий! Новые экспозиции, новые эксперименты и новые обретения ждут Вас за дверями Центра.
		</info>
		<picture>modernart.jpg</picture>
		<picture>modernart1.jpg</picture>
		<district>Советский</district>
		<subjects>Музей искусства</subjects>
		<time>12.00-20.00</time>
		<address>ул. Некрасова, 3</address>
		<email>artmoderncenter@gmail.com</email>
		<cost>5.0</cost>
		<number>+375 17 281-74-79</number>
	</museum>
	<museum>
		<title>Мемориальный музей-мастерская З.И. Азгура</title>
		<info>
			Мемориальный музей-мастерская З.И. Азгура - уникальный музей. Единственный монографический музей в Республике Беларусь, основанный на базе Творческой мастерской Академии художеств СССР и личной мастерской художника. Здание музея построено в 1984 г. по проекту архитектора В. Н. Аладова. С 1999 г. оно включено в Государственный список историко-культурных ценностей Республики Беларусь. С 18 февраля 2000 г. музей открыт для посещения. Концепция музея - мемориальный, монографический художественный - была разработана на стадии его становления и обусловлена спецификой собрания, которое было безвозмездно передано государству семьей скульптора после его смерти. Основной фонд музея насчитывает 4009 единиц (2012) хранения и включает две части: изобразительные коллекции и мемориальный фонд. Музей-мастерская - место памяти, центр актуальных инициатив в музейно-образовательной сфере, пространство творческой лаборатории, в которой реализуют свои самые смелые замыслы современные художники, архитекторы, перформеры, танцоры, музыканты. Традиционные формы взаимодействия с посетителями дополнены инновационными, экспериментальными, интерактивными по формату и наполнению событиями: творческими акциями «День скульптора», «Минск скульптурный», «Открытое искусство», «Ночь музеев» - «Искусство вместо сна», музейно-педагогическими занятиями, мастер-классами, семинарами, авторскими проектами в рамках программ «Игра в классики» и «Музейный театр». Постоянная экспозиция дополнена выставочным проектом «Modern+classic". Современное искусство в традиционном музее».
		</info>
		<picture>azgurmuseum.jpg</picture>
		<picture>azgurmuseum1.jpg</picture>
		<district>Партизанский</district>
		<subjects>Музей искусства</subjects>
		<time>c 10:00 до 18:00</time>
		<address>ул. З.Азгура, 8</address>
		<email>museum.azgur@mail.ru</email>
		<cost>5.0</cost>
		<number>+375 17 541-67-06</number>
	</museum>
	<museum>
		<title>Музей архитектурных миниатюр «Страна мини»</title>
		<info>
Музей архитектурных миниатюр «Страна мини» — идеальный вариант для туристов! Музей — это отличная попытка объять необъятную Беларусь, собрать под одной крышей достопримечательности страны, которые в реальной жизни друг от друга разделяют сотни километров. Специально для вас нами был составлен список 70 важнейших и интереснейших достопримечательностей страны, которые постепенно пополняют музей мини-экспозициями. На сегодня в музее представлено 20 макетов самых значимых объектов архитектурно-исторического наследия Беларуси.Музей «Страна мини» шагает в ногу с современным миром в эпоху технологий. Благодаря этому, в музее представлены интерактивные мультимедийные зоны. Каждый отдельный мини-макет имеет свою интерактивную «фишку». Одна экспозиция — это один мини-мир, в который погружаешься с головой.
		</info>
		<picture>minibelarus.jpg</picture>
		<picture>minibelarus1.jpg</picture>
		<district>Центральный</district>
		<subjects>Другое</subjects>
		<time>11:00 — 20:00</time>
		<address>пр-т Независимости, 25</address>
		<email>info@belarusmini.by</email>
		<cost>15.0</cost>
		<number>+375 29 151-56-70</number>
	</museum>
	<museum>
		<title>Государственный музей истории белорусской литературы</title>
		<info>
Государственный музей истории белорусской литературы — это крупнейший литературный музей страны. Занимается документированием литературного процесса в Беларуси в широком историческом контексте. Расположен в одном из зданий Троицкого предместья, которое является памятником архитектуры XIX ст. Основан 6 ноября 1987 г., открыт для посетителей в 1991 г. В музее хранятся и демонстрируются материалы, которые раскрывают жизнь и творчество известных белорусских писателей. Экспонируется большое количество выставок, среди которых «Васіль Быкаў. Шлях, вызначаны лёсам», «Апякункі паэтычных нябёсаў», «Паэт з Нарачанскага краю» и др. К раритетам музея относятся рукописные и старопечатные издания XVII - XVIII вв., прижизненные книги и личные предметы классиков белорусской литературы, рукописи произведений, книги с автографами, экслибрисы, редкие единицы иконографии, фотоматериалы XIX - первой половины XX вв. Музейная коллекция составляет свыше 50 тысяч единиц хранения. Музей реализует многочисленные выставочные и культурно-образовательные проекты: «Дыяменты прыгожага пісьменства» (к 100-летним юбилеям белорусских писателей), «Рэгіёны» (популяризация литературного-художественного наследия регионов Беларуси), «В музей всей семьей», «Сквозь даль столетий... А. Мицкевич и А. Пушкин» и др. Музей принимает участие в различных международных проектах, сотрудничает с литературными музеями России, Украины, Литвы, Польши и др.
		</info>
		<picture>literaturehistory.jpg</picture>
		<picture>literaturehistory1.jpg</picture>
		<district>Советский</district>
		<subjects>Музей истории</subjects>
		<time>9.30 — 17.30</time>
		<address>ул. М. Богдановича, 13</address>
		<email>bellitmuseum@tut.by</email>
		<cost>6.0</cost>
		<number>+375 17 334-72-61</number>
	</museum>
	<museum>
		<title>Государственный литературно-мемориальный музей Якуба Коласа</title>
		<info>
Музей Якуба Коласа - это ведущий культурный центр, где сберегается история жизни и творчества одного из создателей белорусского языка и литературы. Расположен в доме, где жил Якуб Колас с 1945 по 1956 г. Статус единственного мемориального музея-усадьбы в Минске определяет его уникальность среди прочих литературных музеев столицы. Музей, основной фонд которого составляет 32240 единиц (2012), сохраняет личные вещи поэта и его семьи, книги, рукописи, документы, художественные работы, которые увековечивают образ народного поэта и геро¬ев его произведений. Музей основан 16 августа 1956 г. Открыт для посещения 4 декабря 1959 г. На малой родине Якуба Коласа в Столбцовском районе Минской области работает филиал "Николаевщина", объединяющий мемориальные усадьбы Акинчицы, Ласток, Альбуть, Смольня. Разработан ряд обзорных и тематических экскурсий по экспозиции музея и усадьбах филиала, проводятся театрализованные экскурсии, музейно-педагогические занятия, выставки, творческие встречи с известными людьми, литературно-музыкальные праздники. Известностью пользуется научная конференция "Коласовины".
		</info>
		<picture>yakubkolas.jpg</picture>
		<picture>yakubkolas1.jpg</picture>
		<district>Первомайский</district>
		<subjects>Музей истории</subjects>
		<time>10.00-18.00</time>
		<address>ул. Академическая, 5</address>
		<email>muzeykolas@yandex.ru</email>
		<cost>5.0</cost>
		<number>8 017 284-17-02</number>
	</museum>
	<museum>
		<title>Государственный литературный музей Янки Купалы</title>
		<info>
Один из старейших литературных музеев Беларуси Государственный литературный музей Янки Купалы основан 25.05.1944 г., открыт для посетителей 20.09.1945 г. Музей собирает, хранит, исследует и интерпретирует наследие Янки Купалы (1882-1942). Экспозиция знакомит с жизнью и творчеством Янки Купалы, его ролью в историческом и культурном развитии страны в национальном и европейском контекстах. Значительные проекты последних лет: создание новой постоянной экспозиции, издание каталога "Автографы первого Народного поэта Беларуси Янки Купалы", общественно-культурная акция "Читаем Купалу вместе", выставки к 100-летию пьесы "Павлинка" и 120-летию В. Луцевич Общее количество единиц хранения -51823. Наиболее ценные - автографы, прижизненные издания и портреты Янки Купалы, фотографии и личные вещи поэта и его семьи. Презентация наследия Янки Купалы осуществляется в традиционных и новых формах культурно-образовательной деятельности: обзорные и тематические экскурсии, лекции, вечера, интерактивные проекты для разных категорий посетителей. В рамках партнерства с музеями стран СНГ и Европы реализуются выставочные и культурно-образовательные проекты в России, Литве, Латвии, Армении, Болгарии. В музей входят филиалы “Окопы” (Логойский район) и "Яхимовщина" (Молодечненский район), Купаловские мемориальные заповедники "Вязынка", где ежегодно проходит Республиканский праздник поэзии, песни и народных ремесел, и "Левки" (Оршанский район).
		</info>
		<picture>yankakupala.jpg</picture>
		<picture>yankakupala1.jpg</picture>
		<district>Центральный</district>
		<subjects>Музей истории</subjects>
		<time>9.45 – 17.45</time>
		<address>ул. Янки Купалы, 4</address>
		<email>kupalamuseum@mail.ru</email>
		<cost>6.0</cost>
		<number>+375 17 226-08-39</number>
	</museum>
	<museum>
		<title>Музей «Лошицкая усадьба»</title>
		<info>
Открывшийся в апреле 2015 года музей «Лошицкая усадьба» расположен в окруженном живописным парком бывшем усадебном доме, уникальном памятнике архитектуры XVIII – XIX вв. В состав усадебно-паркового комплекса входят приусадебный флигель, домик сторожа, руины каплицы, здания винокуренного завода и руины мельницы.
Первое письменное упоминание о Лошицкой усадьбе относится к 1557 году. За более чем 400-летнюю историю Лошицей владели многие известные представители дворянских родов, в том числе Друцкие-Горские, Прушинские, Любанские. В имении побывало немало известных и знаковых личностей – драматург Винцент Дунин-Марцинкевич, художник Юзеф Пешка, учёный Николай Вавилов и многие другие.
Своего апогея развитие Лошицы достигло при Евстафии Любанском, который был владельцем имения с 1884 по 1913 гг. При нем имение преобразовалось в одно из лучших губернских хозяйств и стало центром светской жизни. В развитии усадьбы немалую роль сыграла и Ядвига из рода Кеневичей, жена Евстафия. Судьбы Любанских и история их трагической любви теперь овеяны легендами.
В залах усадьбы воссоздана атмосфера светского быта конца XIX – начала XX столетий, можно увидеть восстановленные интерьеры XIX в., изразцовые печи и лепной декор, антикварную мебель и предметы искусства соответствующей эпохи из частных коллекций и собрания Музея истории города Минска. Исторический раздел экспозиции знакомит с этапами становления и развития Лошицы с X века по советское время.
В приусадебном флигеле экспонируется выставка «Колесо времени», где представлены предметы городского и сельского быта конца XIX – середины XX столетий: самовары, утюги, медная утварь, транспортные средства, предметы ткацкого ремесла, воссозданы интерьеры комнаты кухарки и столовой.
		</info>
		<picture>loshytsa.jpg</picture>
		<picture>loshytsa1.jpg</picture>
		<district>Ленинский</district>
		<subjects>Музей истории</subjects>
		<time>11.00 – 19.00</time>
		<address>проезд Чижевских 8-2, 10</address>
		<email>loshytsa@gmail.com</email>
		<cost>8.0</cost>
		<number>+375 17 285 16 86</number>
	</museum>
	<museum>
		<title>Музей книги Национальной библиотеки Беларуси</title>
		<info>
Посетите музей книги, который открылся в Национальной библиотеке Беларуси в сентябре 2006 года.

Узнайте о многовековых традициях белорусского книгопечатания в контексте всемирной истории книги.

Ознакомьтесь с лучшими образцами печатного дела, изданными на протяжении веков в разных уголках мира.

В выставочном зале (288 кв. м) демонстрируется более 300 уникальных книжных памятников: рукописные и старопечатные книги, редкие издания XV–XXI веков.

Среди экспонатов находится жемчужина коллекции – книги Библии (1517–1519) белорусского первопечатника Франциска Скорины.

Современное музейное оснащение, необходимый экспонатам микроклимат, раритетные издания разных времен создают завораживающую атмосферу путешествия в мир книг.

В музее вы также найдете много интересного об истории главной библиотеки страны.
		</info>
		<picture>bookmuseum.jpg</picture>
		<picture>bookmuseum1.jpg</picture>
		<district>Первомайский</district>
		<subjects>Музей истории</subjects>
		<time>10:00 – 18:00</time>
		<address>просп. Независимости, 116</address>
		<email>inbox@nlb.by</email>
		<cost>1.0</cost>
		<number>+375 17 293-25-85</number>
	</museum>
	<museum>
		<title>Музей валунов</title>
		<info>
Музей валунов — парк-музей камней в микрорайоне Уручье.
			
Вся карта Республики Беларусь сделана в масштабе. 1 метр равен реальным 2 км, а 1 метр в высоту равен реальным 100 метрам. Граница страны выполнена в виде низких подстриженных кустиков. Областные города были отмечены 3 голубыми елями (остались только 2 ёлки на месте города Бреста). Реки показаны тропинками, усыпанными мелкими камешками. Весь ландшафт — точная уменьшенная копия ландшафта Республики Беларусь. На территории музея около 2,5 тысяч камней и валунов. Особенно интересно, что те валуны, которые используются для обозначения какой-то возвышенности, были привезены именно из той местности. Также на карте музея обозначены 2 водоема (оз. Нарочь и Заславское водохранилище) в виде бетонных корыт.

Здесь находятся «Крест Стефана Батория», у которого, по преданию, обедал король Великого княжества Литовского во время похода на восток, камень «Дед», привезённый с древнего языческого капища, которое существовало в центре Минска до начала XX века, пограничные валуны, валуны в виде жерновов и многие другие.
		</info>
		<picture>stonemuseum.jpg</picture>
		<picture>stonemuseum1.jpg</picture>
		<district>Первомайский</district>
		<subjects>Другое</subjects>
		<time>Круглосуточно</time>
		<address>аллея Валунов</address>
		<email>Отсутствует</email>
		<cost>0.0</cost>
		<number>Отсутствует</number>
	</museum>
	<museum>
		<title>Музей истории медицины Беларуси</title>
		<info>
Музей был образован Министерством здравоохранения Республики Беларусь в 1990 году. Экспозиция для широкой публики открыта в мае 1993 года.
В экспозиции музея представлены самобытные средства народной медицины и, конечно же, научные подходы к лечению.

Отдельное место в экспозиции занимают материалы посвященные древним религиозным верованиям и злым духам, приносящим болезни. Чтобы защититься от духов, люди использовали амулеты и поклонялись валунам. Увидеть как из себя выглядят валуны, можно в уникальном парке-музее валунов.

В фонде музея хранится свыше 25 тыс. уникальных экспонатов. Особенную ценность представляют редкие документы, фотографии, медицинская литература, мединструменты, награды и личные вещи практиков по охране здоровья Беларуси.

В экспозиции музея собраны картины и диорамы, посвященные медицинской теме. Одна из картин, например, запечатлела сдачу экзамена в университете Падуи первого доктора медицины в Беларуси Франциска Скорина.

Музей поделен на несколько отделов каждый отдел посвящен отдельной теме связанной с медициной.

Основные направления деятельности музея — просветительская работа, организация выставок, историко-медицинские исследования и сбор новых экспонатов.
		</info>
		<picture>medicinemuseum.jpg</picture>
		<district>Московский</district>
		<subjects>Музей истории</subjects>
		<time>10:00 - 17:00</time>
		<address>ул. Фабрициуса, 28</address>
		<email>Отсутствует</email>
		<cost>2.0</cost>
		<number>+375 17 226-39-50</number>
	</museum>
	<museum>
		<title>Музей истории дорожного хозяйства</title>
		<info>
Необычный музей, рассказывающий про историю развития дорог и придорожного сервиса, был создан в 2004 году при Государственном учебном центре «Белдострой».Основные и наиболее интересные разделы выставки: «Дороги Беларуси с древнейших времен», «Дороги белорусских губерний в составе Российской империи в период с XVIII века до начала XX века», «Дороги Беларуси в период Великой Отечественной войны», «Минская кольцевая дорога», «Мосты Беларуси».

Постоянно действующая экспозиция состоит из множества интересных фотографий, раритетов и документов. Посетители выставки могут детально рассмотреть старинные фонари и колокольчики (ими пользовались ямщики), увидеть настоящие верстовые столбы и каплицы, которые устанавливались вдоль дорог.

Например, знали ли вы, зачем пару веков назад все тракты обсаживались деревьями с вполне конкретной целью? Оказывается, это делалось для того, чтобы дорогу можно было найти даже в темноте или во время вьюги. Отсюда же и традиция красить вертикальные ограничители в черно-белый цвет: ведь вдоль трактов, как правило, росли именно березы!

Самый известный памятник дорожному строительству — это, безусловно, верстовые столбы. Название связано с мерой расстояния: верста равнялась современным семи километрам. Такую систему измерения ввели после раздела Речи Посполитой и вхождения белорусских земель в состав Российской империи. До этого в ВКЛ использовались пирамидки. Большой популярностью пользовались стодолы — огромные сараи, куда лошадь заходила вместе с повозкой. Только спустя столетие корчмы и стодолы были заменены почтовыми станциями, где можно было сменить лошадь и переночевать. Невероятно, но факт: в Беларуси сохранилось более пятидесяти таких домиков-станций! Обо всем этом рассказывают экспонаты музея истории дорожного хозяйства в Минске.

Несколько разделов выставки посвящены достижениям современных белорусских дорожников, постоянно меняются и дополняются временные экспозиции. Всего в фондах музея хранится более 8 000 экспонатов, среди которых модели мостов, механизмы карет, и даже фрагмент деревянной дорожной мостовой середины XVII века, которая представлена на открытой площадке перед музеем.
		</info>
		<picture>roadmuseum.jpg</picture>
		<picture>roadmuseum1.jpg</picture>
		<district>Фрунзенский</district>
		<subjects>Музей истории</subjects>
		<time>8:30 - 17:15</time>
		<address>Ул. Кальварийская, 37</address>
		<email>office@beldorstroy.by</email>
		<cost>3.60</cost>
		<number>+375 17 259-86-06</number>
	</museum>
	<museum>
		<title>Центр океанографии «Открытый океан»</title>
		<info>
Центр океанографии открыт для тех, кто любит романтику моря, любознателен и желает узнать больше о подводном и наводном мире. Расположен Центр в малоприметном дворике, однако зайдя внутрь, вы очень удивитесь тому, какая красота здесь находится.

На входе вас встретит скафандр аквалангиста, и далее вы погрузитесь в атмосферу подводного мира. В помещение есть пять залов, каждый из которых посвящен одному из океанов. В центре одной из комнат под ногами вмонтирован компас, который легко покажет, в каком направлении нужно искать каждый океан. В географических зонах есть свои экспонаты: где-то находится кувшин с затонувшего корабля, где-то фотографии исследователей с пингвинами на Южном полюсе. 

Но самое главное — подводные обитатели. В аквариумах вы увидите несколько видов черепах, рыб разных размеров и окрасов, в том числе и прозрачных, карибских креветок и многих других питомцев Центра океанографии. Здесь также проводятся экскурсии, во время которых сотрудники Центра с удовольствием расскажут о подводном мире. 

В «Открытом океане» работают клубы дайверов, подводников, аквариумистов и литературный клуб. Здесь есть кружки для детей, научное сообщество для учащихся и даже детский дайвинг-клуб. В Центре размещена библиотека, небольшой видеозал и электронная лаборатория, а еще специальный аквариумный компьютер, который имитирует грозы, приливы и отливы.
		</info>
		<picture>openocean.jpg</picture>
		<picture>openocean1.jpg</picture>
		<district>Октябрьский</district>
		<subjects>Другое</subjects>
		<time>10:00 - 18:00</time>
		<address>ул. Чкалова, 38</address>
		<email>Отсутствует</email>
		<cost>5.0</cost>
		<number>+375 (29) 333-31-82</number>
	</museum>
	<museum>
		<title>Музейно-промышленный центр трудовой славы МТЗ</title>
		<info>
22 сентября 2017 года широко распахнул свои двери для посетителей Музей Минского тракторного завода - флагмана машиностроения Республики Беларусь.

Наш музей расскажет Вам яркую и насыщенную событиями историю создания Минского тракторного завода, его развития и становления.

Экспозиция музея включает интереснейшие подлинные исторические документы прошлого, а также современные интерактивные элементы.

История нашего музея берет свое начало в 1971 году. Когда была создана первая выставочная экспозиция в виде комнаты трудовой славы.

Современный музей Минского тракторного завода предполагает выполнение следующих задач: 
• создание максимально доступной постоянно действующей базы профориентации и материально-производственной базы для всех категорий и групп обучающихся – школьников, учащихся колледжей и гимназий, студентов и аспирантов как технического, так и гуманитарного направлений; 
• создание оптимальных условий для проведения творческих встреч, связанных с тематикой и профилем музея, приспособленного для единовременного принятия большего числа посетителей; 